{ pkgs, ... }: {  
  i18n.inputMethod = {
    enabled = "fcitx5";
    fcitx5.addons = with pkgs; [
      fcitx5-gtk
      
      fcitx5-chinese-addons
    ];
  };

  xdg.configFile."fcitx5/profile" = {
    # `fcitx5` overwrites its `profile` config file on startup (https://github.com/fcitx/fcitx5/issues/948),
    # and I couldn't figure out how to stop it.
    #
    # In the worst case, it just turns a symbolic link into a regular file. Switching the NixOS config
    # moves the newly created (but identical) file to a backed-up version. Re-logging in makes `fcitx5`
    # change the symbolically-linked config file to a regular file *again*. Now there are two regular files:
    # `profile` and `profile.backup` side-by-side. Another NixOS switch and `home-manager` complains: it
    # wants to move `profile` to `profile.backup`, but `profile.backup` already exists.
    #
    # Skip all this nonsense by force-overwriting `profile` on switch.
    force = true;
    
    # Generated by `fcitx5-configtool`.
    text = ''
      [Groups/0]
      # Group Name
      Name=Default
      # Layout
      Default Layout=us
      # Default Input Method
      DefaultIM=pinyin

      [Groups/0/Items/0]
      # Name
      Name=keyboard-us
      # Layout
      Layout=

      [Groups/0/Items/1]
      # Name
      Name=pinyin
      # Layout
      Layout=

      [GroupOrder]
      0=Default''\n
    '';
  };
}
